name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, llvm-tools, rust-src
          targets: x86_64-unknown-none

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Format check
        run: cargo fmt --all -- --check

      - name: Build (host)
        run: cargo build -p r-os

      - name: Build (kernel, no_std)
        env:
          CARGO_PROFILE_DEV_PANIC: abort
        run: cargo build -p kernel --target x86_64-unknown-none -Z build-std=core,compiler_builtins -Z unstable-options -Cpanic=abort

      - name: Test
        run: cargo test --workspace --exclude kernel
